#!/bin/sh



# postinst script for webpy-example
#
# see: dh_installdeb(1)

#_DEB_SYSTEMD_HELPER_DEBUG=1

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# source debconf library
#. /usr/share/debconf/confmodule

# For user-services only, for earch target an extra section! for system-services user deb-systemd*
# put in full unit-name. for example "mkbackup@hourly.service"


case "$1" in

    configure)
        id vmail || useradd -r -d /var/mail -s /sbin/nologin -c "Virtual mailbox" vmail
        [ ! -e "/var/mail/virtual/Neue Mails" ] && mv "/var/mail/virtual/Neue_Mails" "/var/mail/virtual/Neue Mails"
        [ ! -e "/var/mail/virtual/Ungesehene Mails" ] && mv "/var/mail/virtual/Ungesehene_Mails" "/var/mail/virtual/Ungesehene Mails"
        
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;

esac

